# Generated by Django 6.0.1 on 2026-01-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=200)),
                ('end_time', models.DateTimeField()),
                ('left_image', models.ImageField(upload_to='deals/')),
                ('right_image', models.ImageField(upload_to='deals/')),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('button_link', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
