# Generated by Django 6.0.1 on 2026-01-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_hotdeal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotdeal',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='hotdeal',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='hotdeal',
            name='left_image',
        ),
        migrations.RemoveField(
            model_name='hotdeal',
            name='right_image',
        ),
        migrations.AddField(
            model_name='hotdeal',
            name='products',
            field=models.ManyToManyField(blank=True, to='shop.product'),
        ),
    ]
