# Generated by Django 6.0.1 on 2026-01-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_hotdeal_button_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_hot_deal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
