# Generated by Django 6.0.1 on 2026-01-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_payment_status_order_status_order_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='profile.png', upload_to='profiles/'),
        ),
    ]
