# Generated by Django 4.2 on 2026-02-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_productcategory_description_productcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
